import React from 'react';
import { 
  FileText, Sparkles, Zap, BarChart2, Compass, Activity, ShieldCheck 
} from 'lucide-react';

export interface AiMappingDetails {
  capabilityId: string;
  capabilityNameEn: string;
  capabilityNameZh: string;
  capabilityDescEn: string;
  capabilityDescZh: string;
  icon: React.ComponentType<{ className?: string }>;
  functionNameEn: string;
  functionNameZh: string;
  whySuitableEn: string;
  whySuitableZh: string;
  benefitsEn: string;
  benefitsZh: string;
  sustContributionEn: string;
  sustContributionZh: string;
  expectedOutcomeEn: string;
  expectedOutcomeZh: string;
}

export const AI_MAPPING_DB: Record<string, AiMappingDetails> = {
  'rec-1': {
    capabilityId: 'summarization',
    capabilityNameEn: 'AI Summarization',
    capabilityNameZh: 'AI 摘要生成',
    capabilityDescEn: 'Automatically summarize documents, reports, policies, training content, and ESG materials.',
    capabilityDescZh: '自动总结文件、报告、培训内容与ESG资料。',
    icon: FileText,
    functionNameEn: 'AI Candidate Evaluation',
    functionNameZh: 'AI 候选人评估',
    whySuitableEn: 'Using semantic analysis to screen massive volumes of CVs for Green HR project tags.',
    whySuitableZh: '应用语义分析与实体识别技术，在海量简历数据中精准、无感筛选环保/ESG领域专业人才。',
    benefitsEn: 'Dramatically reduces candidate screen times and identifies hidden sustainability champions.',
    benefitsZh: '大幅缩减招聘专员搜寻履历时间，精确提取隐藏的低碳项目背景。',
    sustContributionEn: 'Speeds up Green HR talent pipeline acquisition.',
    sustContributionZh: '加速企业绿色低碳人才梯队建设。',
    expectedOutcomeEn: 'Reduce recruitment workload and improve candidate screening efficiency.',
    expectedOutcomeZh: '降低招聘工作量并提升筛选效率。'
  },
  'rec-2': {
    capabilityId: 'recommendation',
    capabilityNameEn: 'AI Recommendation Engine',
    capabilityNameZh: 'AI 智能推荐',
    capabilityDescEn: 'Provide personalized recommendations for employees, managers, and HR teams.',
    capabilityDescZh: '向员工、管理者与HR提供个性化建议。',
    icon: Sparkles,
    functionNameEn: 'AI Mindset Profiling & Selection',
    functionNameZh: 'AI 绿色价值观对准',
    whySuitableEn: 'Formulates smart candidate questionnaires and adaptive scenario evaluations.',
    whySuitableZh: '根据企业低碳行动目标，自学并编排多维情景面试题，客观刻画其亲环境行为倾向。',
    benefitsEn: 'Ensures candidates share matching non-financial corporate sustainability core values.',
    benefitsZh: '防范应聘时的纸上漂绿言论，确保新进员工对可持续发展具有发自内心的价值认求。',
    sustContributionEn: 'Maintains long-term green culture integrity.',
    sustContributionZh: '从源头保障绿色企业文化的纯正性与共识深度。',
    expectedOutcomeEn: 'Automate value profiling and increase candidate alignment with Green HR values.',
    expectedOutcomeZh: '自动生成价值观评估画像，提高候选人与绿色企业文化的契合度。'
  },
  'rec-3': {
    capabilityId: 'automation',
    capabilityNameEn: 'Workflow Automation',
    capabilityNameZh: '流程自动化',
    capabilityDescEn: 'Reduce repetitive manual work and administrative burden.',
    capabilityDescZh: '减少重复性工作与管理负担。',
    icon: Zap,
    functionNameEn: 'Zero-Paper Pipeline Orchestrator',
    functionNameZh: '无纸化智能日程编排',
    whySuitableEn: 'Automates meeting coordinates, calendar alignments, and virtual onboarding kits distribution.',
    whySuitableZh: '一键协调跨部门考官时空档期，向待入职员工全程分发无纸化合同、绿电通勤指南。',
    benefitsEn: 'Excludes all paper print friction in administrative HR stages.',
    benefitsZh: '全流程消除入职纸张打印与物理耗损需求，降低行政事务的时间耗散。',
    sustContributionEn: 'Direct Scope 3 reduction in workspace materials.',
    sustContributionZh: '直接消减人力资源部门本阶段的办公纸张及印刷碳足迹。',
    expectedOutcomeEn: 'Minimize recruitment administration and scale environmental digital processes.',
    expectedOutcomeZh: '极力缩减线下流转流程，极大提升绿色运营敏捷度。'
  },
  'train-1': {
    capabilityId: 'recommendation',
    capabilityNameEn: 'AI Recommendation Engine',
    capabilityNameZh: 'AI 智能推荐',
    capabilityDescEn: 'Provide personalized recommendations for employees, managers, and HR teams.',
    capabilityDescZh: '向员工、管理者与HR提供个性化建议。',
    icon: Sparkles,
    functionNameEn: 'Precision Green Course Dispatch',
    functionNameZh: '精准绿色微课推荐',
    whySuitableEn: 'Aligns course recommendations with specific roles operational carbon risk elements.',
    whySuitableZh: '分析员工日常岗位中的能耗漏洞，精准计算并推荐对位的低碳合规微课。',
    benefitsEn: 'Boosts learning relevance and ensures employees gain role-specific ESG knowledge.',
    benefitsZh: '避免盲目培训，让业务骨干学到切中其实际职能的能效改进干货。',
    sustContributionEn: 'Drives systemic pro-environmental behaviors.',
    sustContributionZh: '有效赋能基层业务线，消除具体岗位上的物理能耗重叠摩擦。',
    expectedOutcomeEn: 'Enhance operational learning precision and save administrative review cycles.',
    expectedOutcomeZh: '提升学员学习关联性，全自动覆盖岗位减碳应知应会。'
  },
  'train-2': {
    capabilityId: 'analysis',
    capabilityNameEn: 'AI Data Analysis',
    capabilityNameZh: 'AI 数据分析',
    capabilityDescEn: 'Analyze sustainability metrics, employee participation, ESG indicators, and behavioral trends.',
    capabilityDescZh: '分析可持续发展数据、参与率与行为趋势。',
    icon: BarChart2,
    functionNameEn: 'AI Learning Analytics',
    functionNameZh: 'AI 学习分析',
    whySuitableEn: 'Monitors non-linear learning logs of thousands of team members simultaneously.',
    whySuitableZh: '无感追踪、聚合数千名员工的看课、作答行为，并深度建模分析学分断层位置。',
    benefitsEn: 'Pinpoints exactly where and why users stop course progress.',
    benefitsZh: '及时捕捉课程设计硬伤，智能标记并协助修改难以理解的ESG法规习题。',
    sustContributionEn: 'Improves ESG guidelines integration in standard operations.',
    sustContributionZh: '显著提高企业ESG年度受训达标率与意识留存时长。',
    expectedOutcomeEn: 'Improve training completion rates and learning effectiveness.',
    expectedOutcomeZh: '提高培训完成率与学习效果。'
  },
  'train-3': {
    capabilityId: 'generation',
    capabilityNameEn: 'AI Content Generation',
    capabilityNameZh: 'AI 内容生成',
    capabilityDescEn: 'Generate training materials, communication messages, sustainability campaigns, and management reports.',
    capabilityDescZh: '自动生成培训内容、宣传材料及管理报告。',
    icon: Compass,
    functionNameEn: 'High-Empathy Reminder Nudger',
    functionNameZh: '高同理心习惯激活提醒',
    whySuitableEn: 'Generates non-hostile reminders according to custom group psychological states.',
    whySuitableZh: '一键自动润色、生成温和、富有亲自然共情力的提醒内容，降低常规催审的管理者抵触情绪。',
    benefitsEn: 'Avoids notification fatigue from generic copy-pasted corporate emails.',
    benefitsZh: '彻底避免僵硬死板的批量通报对组织氛围的负调节，用柔性设计推动意识觉醒。',
    sustContributionEn: 'Fosters organic pro-environmental behaviors.',
    sustContributionZh: '显著增强员工对环保课程自发续学意愿，而非被迫打卡受罪。',
    expectedOutcomeEn: 'Mitigate completion resistance and optimize communication workflows.',
    expectedOutcomeZh: '消减内部催审抗阻，优化组织间日常微沟通流。'
  },
  'perf-1': {
    capabilityId: 'automation',
    capabilityNameEn: 'Workflow Automation',
    capabilityNameZh: '流程自动化',
    capabilityDescEn: 'Reduce repetitive manual work and administrative burden.',
    capabilityDescZh: '减少重复性工作与管理负担。',
    icon: Zap,
    functionNameEn: 'Wireless Carbon API Extractor',
    functionNameZh: '多源无感能耗采集接入',
    whySuitableEn: 'Coordinates and merges device feeds, smart meters and transit records dynamically.',
    whySuitableZh: '定时调度、自动爬取并合并包括双面打印服务器、差旅系统与智能电表的异构日志条项。',
    benefitsEn: 'Replaces error-prone manual Excel aggregation with clean API structures.',
    benefitsZh: '终结不同行政职能部门间Excel表格格式打架、数据漏登或手工漏账的问题。',
    sustContributionEn: 'Builds trusted and audit-ready decarbonization records.',
    sustContributionZh: '帮助企业构建兼具数学自恰性、不可拆分、真实可追溯的Scope 1~3碳总账。',
    expectedOutcomeEn: 'Reduce reporting effort and improve data accuracy.',
    expectedOutcomeZh: '减少报告工作量并提高数据准确性。'
  },
  'perf-2': {
    capabilityId: 'insights',
    capabilityNameEn: 'AI Behavioral Insights',
    capabilityNameZh: 'AI 行为洞察',
    capabilityDescEn: 'Identify patterns in employee sustainability participation and workplace habits.',
    capabilityDescZh: '分析员工绿色行为模式与参与规律。',
    icon: Activity,
    functionNameEn: 'Pro-environmental Behavioral Insights',
    functionNameZh: 'AI 亲环境行为洞察',
    whySuitableEn: 'Surveys physical behaviors and discovers structural hurdles in local facilities.',
    whySuitableZh: '挖掘底层出行打卡、餐盘光盘与纸张消耗的时空振幅规律，智能标记出缺乏便利垃圾分类桶的物理卡点。',
    benefitsEn: 'Finds exactly what obstacles employees encounter when trying to act sustainably.',
    benefitsZh: '将绿色习惯阻力诊断从“玄学推演”上升为“物理环境科学适配”。',
    sustContributionEn: 'Strengthens grassroots pro-environmental engagement indexes.',
    sustContributionZh: '有的放矢改善办公硬件，成倍放大全员低碳参与的实际收益。',
    expectedOutcomeEn: 'Identify engagement patterns and strengthen pro-environmental behavior initiatives.',
    expectedOutcomeZh: '识别参与规律并提升亲环境行为促进效果。'
  },
  'perf-3': {
    capabilityId: 'summarization',
    capabilityNameEn: 'AI Summarization',
    capabilityNameZh: 'AI 摘要生成',
    capabilityDescEn: 'Automatically summarize documents, reports, policies, training content, and ESG materials.',
    capabilityDescZh: '自动总结文件、报告、培训内容与ESG资料。',
    icon: FileText,
    functionNameEn: 'ESG Disclosure Coprocessor',
    functionNameZh: '低碳年度报告与ESG核回',
    whySuitableEn: 'Synthesizing thousands of fragmented personnel point ledgers into audit-ready GRI formats.',
    whySuitableZh: '在极短时间内，将全员十万条琐碎低碳打卡记录与千吨级碳抵消事件，整段编译成符合GRI规范的环境数据陈述段。',
    benefitsEn: 'Ensures data consistency and avoids manual compilation errors during reporting.',
    benefitsZh: '全流程防范主观注水，确保披露数据有数可查、链条严密、满足合规抽检。',
    sustContributionEn: 'Enhances administrative reporting transparency.',
    sustContributionZh: '促进高可靠非财务绩效披露，帮助企业平稳渡过ESG抽查，收获溢价认同。',
    expectedOutcomeEn: 'Accelerate periodic review times and boost reporting compliance.',
    expectedOutcomeZh: '极大收敛评估 and 核查流转时间，自动生成对内对外ESG年报备选文稿。'
  },
  'rew-1': {
    capabilityId: 'predictive',
    capabilityNameEn: 'AI Predictive Analytics',
    capabilityNameZh: 'AI 预测分析',
    capabilityDescEn: 'Forecast engagement trends, sustainability risks, and organizational challenges.',
    capabilityDescZh: '预测参与趋势、潜在风险与组织问题。',
    icon: Compass,
    functionNameEn: 'Reward Utilization Forecaster',
    functionNameZh: '绿色积分礼品动态仿真',
    whySuitableEn: 'Leverages historical redemption curves to balance points pool and merchandise stock.',
    whySuitableZh: '通过分析历史碳点累积和礼品消耗速度模型，预测各低碳礼券、林业契证的对位需求起落。',
    benefitsEn: 'Prevents budget overruns and ensures highly motivational goods are never out-of-stock.',
    benefitsZh: '大幅削减企业自购绿色好礼的闲置折旧损失，确保热门激励品类不爆仓、不断货。',
    sustContributionEn: 'Optimizes resource utilization dynamically.',
    sustContributionZh: '实现绿色积分系统预算高效平滑周转，激励心流始终处于高昂水平。',
    expectedOutcomeEn: 'Reduce procurement overheads and maintain optimal incentive velocity.',
    expectedOutcomeZh: '优化积分兑换平准率，消除采购冗余物资，规避不必要的二次碳足迹支出。'
  },
  'rew-2': {
    capabilityId: 'insights',
    capabilityNameEn: 'AI Behavioral Insights',
    capabilityNameZh: 'AI 行为洞察',
    capabilityDescEn: 'Identify patterns in employee sustainability participation and workplace habits.',
    capabilityDescZh: '分析员工绿色行为模式与参与规律。',
    icon: Activity,
    functionNameEn: 'Points De-fraud Protection',
    functionNameZh: '积分漏账与虚假打卡智能合规审计',
    whySuitableEn: 'Identifies behavioral anomalies such as multiple daily check-ins for the same elevator.',
    whySuitableZh: '分析位置指纹与物理事件时序关联，发现并筛除诸如“多人在同时间段上传同一杯具照片”等机械欺瞒。',
    benefitsEn: 'Protects the integrity of the carbon points micro-incentive ecosystem from gamification hacks.',
    benefitsZh: '保证绿色积分池的数学硬合规，捍卫认真执行低碳生活的员工尊严。',
    sustContributionEn: 'Prevents pro-environmental program moral hazard issues.',
    sustContributionZh: '剔除虚无漂水积分，牢固护卫企业对环境利益让渡的底盘。',
    expectedOutcomeEn: 'Erase cheating vulnerabilities and solidifies green program integrity.',
    expectedOutcomeZh: '锁定打卡公正公信，规避福利机制被钻空子。'
  },
  'rew-3': {
    capabilityId: 'automation',
    capabilityNameEn: 'Workflow Automation',
    capabilityNameZh: '流程自动化',
    capabilityDescEn: 'Reduce repetitive manual work and administrative burden.',
    capabilityDescZh: '减少重复性工作与管理负担。',
    icon: Zap,
    functionNameEn: 'Incentive Delivery Bridge',
    functionNameZh: '奖品无感下发与契证铸造',
    whySuitableEn: 'Instantly dispatches electronic tokens or connects API endpoints to logistics partners.',
    whySuitableZh: '当用户达成“绿能种树”或“星级兑奖”时，零秒生成第三方数字消费凭账，或自动在林场系统铸造碳资产冠名产权契证。',
    benefitsEn: 'Relieves Green HR team members from heavy packing, manual emailing or coupon distribution.',
    benefitsZh: '免除行政专员逐行录发卡、确认寄送细节的累赘体力劳。',
    sustContributionEn: 'Eliminates redundant processing friction.',
    sustContributionZh: '用完全闭闭环的云端下发体系消除额外的手动搬运，提供光速满足感。',
    expectedOutcomeEn: 'Enhance employee reward experience and eliminate clerical paper routing.',
    expectedOutcomeZh: '消除实物发券，全面进入即兑即用数字化绿色心流体验。'
  },
  'eng-1': {
    capabilityId: 'insights',
    capabilityNameEn: 'AI Behavioral Insights',
    capabilityNameZh: 'AI 行为洞察',
    capabilityDescEn: 'Identify patterns in employee sustainability participation and workplace habits.',
    capabilityDescZh: '分析员工绿色行为模式与参与规律。',
    icon: Activity,
    functionNameEn: 'Eco-engagement Trend Profiler',
    functionNameZh: '低碳体验极点追踪',
    whySuitableEn: 'Spots collective participation bottlenecks across workspace calendar periods.',
    whySuitableZh: '追踪写字楼早中晚不同用能热点与打卡履约率，预测在特定高温酷暑季节或连绵雨天全员减碳参与趋势。',
    benefitsEn: 'Allows campaign leads to adaptively run team-spirit nudges during slump periods.',
    benefitsZh: '提前预警打卡冷落和习惯退化期，帮助HR进行干预。',
    sustContributionEn: 'Direct support to employee Pro-Environmental Behavior (PEB).',
    sustContributionZh: '精准修复特定场景下的环境惰性，缩减高发环境浪费频次。',
    expectedOutcomeEn: 'Identify engagement patterns and strengthen pro-environmental behavior initiatives.',
    expectedOutcomeZh: '识别参与规律并提升亲环境行为促进效果。'
  },
  'eng-2': {
    capabilityId: 'generation',
    capabilityNameEn: 'AI Content Generation',
    capabilityNameZh: 'AI 内容生成',
    capabilityDescEn: 'Generate training materials, communication messages, sustainability campaigns, and management reports.',
    capabilityDescZh: '自动生成培训内容、宣传材料及管理报告。',
    icon: Compass,
    functionNameEn: 'Green HR Copy & Rule Wizard',
    functionNameZh: '绿色打卡排位战企划魔术师',
    whySuitableEn: 'Learns standard structures of successful gamified challenges to write customized rules instantly.',
    whySuitableZh: '自动吸纳业内领军企业的前沿低碳运营策略，一秒生成极具吸引力、符合跨部门竞速规则的文案。',
    benefitsEn: 'Allows constant updates to green activities catalog without planning drag.',
    benefitsZh: '解禁HR策划荒，让月月活动翻新，持续维系全员低碳关注。',
    sustContributionEn: 'Catalyzes workplace eco-social contagion.',
    sustContributionZh: '在集团内制造轻快的减碳社会风尚，使低碳实践不再死板说教。',
    expectedOutcomeEn: 'Accelerate launch-times of team environmental events and save HR drafting hours.',
    expectedOutcomeZh: '降低活动筹备周期，输出极具创意性、年轻化团队打卡企划。'
  },
  'eng-3': {
    capabilityId: 'summarization',
    capabilityNameEn: 'AI Summarization',
    capabilityNameZh: 'AI 摘要生成',
    capabilityDescEn: 'Automatically summarize documents, reports, policies, training content, and ESG materials.',
    capabilityDescZh: '自动总结文件、报告、培训内容与ESG资料。',
    icon: FileText,
    functionNameEn: 'Eco-complaints Semantic Cluster',
    functionNameZh: '绿色建议与阻力民意聚焦',
    whySuitableEn: 'Structures thousands of text feedbacks into neat conceptual pain pillars.',
    whySuitableZh: '跨文本语区提炼、聚合全员对绿色制度或大楼用电策略的不适，精准合并相似痛点民意。',
    benefitsEn: 'Reveals systematic operational layout blockages easily ignored by executives.',
    benefitsZh: '一针见血找到究竟是“自带饭盒缺少洗涤池”还是“走廊熄灯太黑”，消除行动微梗阻。',
    sustContributionEn: 'Guards collaborative corporate trust loops.',
    sustContributionZh: '打通自下而上的无惧真情诉求，促进企业制度的高效迭代与员工良性自驱。',
    expectedOutcomeEn: 'Synthesize open-text feedback lists into actionable environment change-cards.',
    expectedOutcomeZh: '瞬间对焦物理或政策屏障，大幅降低习惯纠删摩擦力。'
  },
  'comp-1': {
    capabilityId: 'summarization',
    capabilityNameEn: 'AI Summarization',
    capabilityNameZh: 'AI 摘要生成',
    capabilityDescEn: 'Automatically summarize documents, reports, policies, training content, and ESG materials.',
    capabilityDescZh: '自动总结文件、报告、培训内容与ESG资料。',
    icon: FileText,
    functionNameEn: 'Fuzzy Voucher Checker',
    functionNameZh: '不规范采购与漂绿风险审计',
    whySuitableEn: 'Examines extensive commercial supply logs against sustainability certification standards automatically.',
    whySuitableZh: '在财签流里对造纸、差旅发票进行逻辑语义推导研究，判定是否暗含合规赤字、过载印刷或漂绿嫌疑。',
    benefitsEn: 'Shields executive board from deep regulatory or image litigation hazards.',
    benefitsZh: '一秒揪出高耗劣质办公杂件购销或假环保凭据，筑牢安全防线。',
    sustContributionEn: 'Shields non-financial database trust.',
    sustContributionZh: '防止形式主义环保或合规飞线漏洞对企业商誉造成潜在毁灭性伤害。',
    expectedOutcomeEn: 'Eradicate commercial compliance slippage and reduce document verification labor.',
    expectedOutcomeZh: '消除绿色行政流程的账实不一，高精准排查潜在伪绿色风险。'
  },
  'comp-2': {
    capabilityId: 'automation',
    capabilityNameEn: 'Workflow Automation',
    capabilityNameZh: '流程自动化',
    capabilityDescEn: 'Reduce repetitive manual work and administrative burden.',
    capabilityDescZh: '减少重复性工作与管理负担。',
    icon: Zap,
    functionNameEn: 'Scope Ledger Consolidation Engine',
    functionNameZh: '跨级能效流水多线对账',
    whySuitableEn: 'Ingests dynamic environmental datasets across secondary supply points and office subsystems.',
    whySuitableZh: '设计持久定时管道对大楼各配电模块、热能阀和食堂采购进行底本提取和归一化处理。',
    benefitsEn: 'Removes traditional manual copy-pasting of spreadsheet indices.',
    benefitsZh: '极高速度排除跨多地点异构口径对不齐、数值打架的人力耗散。',
    sustContributionEn: 'Reinforces consistent dual-materiality data schemas.',
    sustContributionZh: '极大缩短对能效日志漏项、空缺的识别时长，实现财务级ESG实账校验。',
    expectedOutcomeEn: 'Enhance data-gathering speeds and ensure flawless mathematical symmetry.',
    expectedOutcomeZh: '实现跨业务条线零摩擦集成对数，确保能耗审计过程全自动运作。'
  },
  'comp-3': {
    capabilityId: 'predictive',
    capabilityNameEn: 'AI Predictive Analytics',
    capabilityNameZh: 'AI 预测分析',
    capabilityDescEn: 'Forecast engagement trends, sustainability risks, and organizational challenges.',
    capabilityDescZh: '预测参与趋势、潜在风险与组织问题。',
    icon: Compass,
    functionNameEn: 'ESG Audit Mock sandbox',
    functionNameZh: 'GRI合规成熟度压力测试',
    whySuitableEn: 'Maps internal employee participation levels against double-materiality disclosure targets.',
    whySuitableZh: '模拟第三方鉴证机构的极端穿透尺度，评估公司现有习惯指数和避碳归一契证是否符合核减指标。',
    benefitsEn: 'Guarantees perfect alignment with official standard checklists before board submission.',
    benefitsZh: '提前捕足非财务账户中可能被挑战的数据链残缺或哈希断裂。',
    sustContributionEn: 'Protects critical corporate social investment reputation.',
    sustContributionZh: '从根本上建立全供应链、全员工行为层面的坚实信用背书，底色自恰。',
    expectedOutcomeEn: 'Confidently anticipate disclosure targets and prevent rating degradation.',
    expectedOutcomeZh: '将审计阻力降低大半，防范重大历史遗存核查盲区。'
  },
  'rep-1': {
    capabilityId: 'summarization',
    capabilityNameEn: 'AI Summarization',
    capabilityNameZh: 'AI 摘要生成',
    capabilityDescEn: 'Automatically summarize documents, reports, policies, training content, and ESG materials.',
    capabilityDescZh: '自动总结文件、报告、培训内容与ESG资料。',
    icon: FileText,
    functionNameEn: 'Regulatory Mapping Coordinator',
    functionNameZh: '全球披露法条语义核检',
    whySuitableEn: 'Regularly audits international CSRD, GRI, SASB updates to flag template offsets.',
    whySuitableZh: '定时拉取各区域减排核准新规与披露因子，自动研读出公式变体并提醒数据库升级。',
    benefitsEn: 'Frees administrative managers from manually checking complex statutory updates.',
    benefitsZh: '避免由于法案修订滞后，使用过时的能耗转换率导致在年报中酿成误导性风险。',
    sustContributionEn: 'Dynamic synchronization with environmental statutory frameworks.',
    sustContributionZh: '使组织环境资产价值结算框架保持分钟级对齐，时刻走在行业合规前沿。',
    expectedOutcomeEn: 'Avert out-of-date emission factor calculation issues seamlessly.',
    expectedOutcomeZh: '规避因法规更迭而算错年度碳当量的重大非财务偏差风险。'
  },
  'rep-2': {
    capabilityId: 'analysis',
    capabilityNameEn: 'AI Data Analysis',
    capabilityNameZh: 'AI 数据分析',
    capabilityDescEn: 'Analyze sustainability metrics, employee participation, ESG indicators, and behavioral trends.',
    capabilityDescZh: '分析可持续发展数据、参与率与行为趋势。',
    icon: BarChart2,
    functionNameEn: 'Carbon Fusion Analytics Core',
    functionNameZh: '行为-用能双向异构合并',
    whySuitableEn: 'Melds human behaviors logs (Scope 3 commute) and building physical consumption assets (Scope 2 space).',
    whySuitableZh: '智能拟合全员每天数十万次环境习惯碎片与智能电网物理有功功率波形，精确析出管理效能。',
    benefitsEn: 'Replaces generic guessing of Green HR benefits with solid mathematical correlation models.',
    benefitsZh: '精确计算出写字楼“下午三点温度调升一度”和“倡导自带水杯”到底各自引流了多少降碳增益。',
    sustContributionEn: 'Establishes rigid scientific correlation in carbon management.',
    sustContributionZh: '揭示员工行为调差对企业综合用能基线的直接定量因果链。',
    expectedOutcomeEn: 'Formulate robust correlation graphs and wipe out hours of manual charting.',
    expectedOutcomeZh: '自动化聚合跨维度能效数据，提供一站式无缝可视化校验底板。'
  },
  'rep-3': {
    capabilityId: 'automation',
    capabilityNameEn: 'Workflow Automation',
    capabilityNameZh: '流程自动化',
    capabilityDescEn: 'Reduce repetitive manual work and administrative burden.',
    capabilityDescZh: '减少重复性工作与管理负担。',
    icon: Zap,
    functionNameEn: 'Scientific CO2e Translator',
    functionNameZh: '温室气体当量全因子代算器',
    whySuitableEn: 'Converts disparate metrics (grams of paper, mileage, device hours) to unified CO2e equivalent weight.',
    whySuitableZh: '后台部署智能折算算子，自动查表并匹配所属区域在特定年份的网格排放系数进行科学折算。',
    benefitsEn: 'Eliminates math errors and human discrepancies in spreadsheet calculations.',
    benefitsZh: '彻底替代行政人员痛苦的手工去套算碳排放当量的枯燥、易出错工作。',
    sustContributionEn: 'Guarantees calculation accuracy of corporate scope databases.',
    sustContributionZh: '确保向董事会或对外发布资料中的所有一揽子环保减排数字分毫不差。',
    expectedOutcomeEn: 'Ensure complete carbon tracking precision and release administrative labor.',
    expectedOutcomeZh: '高精度换算非标习惯打卡为标准气候绩效指标，节省大量公式转换摩擦。'
  },
  'cult-1': {
    capabilityId: 'insights',
    capabilityNameEn: 'AI Behavioral Insights',
    capabilityNameZh: 'AI 行为洞察',
    capabilityDescEn: 'Identify patterns in employee sustainability participation and workplace habits.',
    capabilityDescZh: '分析员工绿色行为模式与参与规律。',
    icon: Activity,
    functionNameEn: 'Team Sentiment & Culture Indexer',
    functionNameZh: '绿色组织文化指数洞察',
    whySuitableEn: 'Leverages sentiment mining from internal surveys to spot hidden low-carbon burnouts.',
    whySuitableZh: '应用轻量语义提取与极性判断，剖析员工在进行强制性打卡时的不解、反弹或麻木程度。',
    benefitsEn: 'Helps dynamic adjustments of Green HR push campaigns to build authentic consensus.',
    benefitsZh: '及时向管理层反馈是否环保积分定价在员工心智里过标，或打卡限制太多从而对行为造成卡顿。',
    sustContributionEn: 'Nurtures a genuinely supportive, unforced sustainability workspace.',
    sustContributionZh: '杜绝强制绿色指标催生出的“形式应付”，培养真正的全员亲环境凝聚力。',
    expectedOutcomeEn: 'Formulate qualitative culture maturation indexes rather than raw checks.',
    expectedOutcomeZh: '精确评估并输出员工绿色文化的真诚与粘性，实现温和的环境自驱治理。'
  },
  'cult-2': {
    capabilityId: 'recommendation',
    capabilityNameEn: 'AI Recommendation Engine',
    capabilityNameZh: 'AI 智能推荐',
    capabilityDescEn: 'Provide personalized recommendations for employees, managers, and HR teams.',
    capabilityDescZh: '向员工、管理者与HR提供个性化建议。',
    icon: Sparkles,
    functionNameEn: 'SNA Advocate Identifier',
    functionNameZh: '低碳骨干火种智能发掘',
    whySuitableEn: 'Executes relational tracking in workspace informal messaging networks to isolate change catalyst advocates.',
    whySuitableZh: '通过分析去中心化的企业社区分享指数，挖掘出那些在社群内具有积极号召力的亲自然环保积极分子。',
    benefitsEn: 'Allows targeted distribution of privileges or honor assets to maximize follow-up peer imitation.',
    benefitsZh: '利用意见领袖的带动力和无形号召，极大地省去官僚式死硬宣贯，大幅降低推广成本。',
    sustContributionEn: 'Improves group pro-environmental contagion.',
    sustContributionZh: '搭建更具活力的环境变革骨干社群，推动组织文化自驱裂变。',
    expectedOutcomeEn: 'Locate local leadership nodes and optimize change agent effectiveness.',
    expectedOutcomeZh: '识别并激励无形组织网中低耗避碳催化者，最大化圈层从众降碳涟漪效应。'
  },
  'cult-3': {
    capabilityId: 'generation',
    capabilityNameEn: 'AI Content Generation',
    capabilityNameZh: 'AI 内容生成',
    capabilityDescEn: 'Generate training materials, communication messages, sustainability campaigns, and management reports.',
    capabilityDescZh: '自动生成培训内容、宣传材料及管理报告。',
    icon: Compass,
    functionNameEn: 'Campaign Achievements Artist',
    functionNameZh: '环宣战报与成就海报全自排版',
    whySuitableEn: 'Transforms boring metrics spreadsheets into gorgeous graphic leaflets.',
    whySuitableZh: '读取每周光盘、少开私车、走楼梯省电排行榜，一秒合成极富视觉张力、高荣誉载量的数据投屏。',
    benefitsEn: 'Allows continuous spotlighting of sustainability heroes with zero design budget overheads.',
    benefitsZh: '无需额外美工设计经费，时刻向全楼分发最潮流、最具亲和力的低碳榜样事迹。',
    sustContributionEn: 'Amplifies prestige loops of daily sustainable actions.',
    sustContributionZh: '通过放大组织社会赞许，为执行低碳习惯的员工提供丰富的荣誉资产，维护行动惯性。',
    expectedOutcomeEn: 'Save continuous layout prep hours and maintain dynamic office highlight channels.',
    expectedOutcomeZh: '自动汇总降碳英雄榜，摆脱重复性排版耗尽内部宣发意志的恶性循环。'
  },
  'lead-1': {
    capabilityId: 'summarization',
    capabilityNameEn: 'AI Summarization',
    capabilityNameZh: 'AI 摘要生成',
    capabilityDescEn: 'Automatically summarize documents, reports, policies, training content, and ESG materials.',
    capabilityDescZh: '自动总结文件、报告、培训内容与ESG资料。',
    icon: FileText,
    functionNameEn: 'ESG Priority Synthesizer',
    functionNameZh: '高层战略意图提炼与合规解算',
    whySuitableEn: 'Integrates corporate financial limits, sustainability goals, and market mandates into structural programs.',
    whySuitableZh: '提炼董事、CEO的决策与非财务关切，并跟基层实践守则进行最直接、最透明的目标映射。',
    benefitsEn: 'Ensures bottom-up programs are fully funded by aligning with top-down corporate interest pillars.',
    benefitsZh: '避免绿色转型流于纸上谈兵，确保低碳微动作具备实质性董事会战略分量。',
    sustContributionEn: 'Secures administrative resources to pro-environmental campaigns.',
    sustContributionZh: '打通顶层资源分配，赋予一线部门常态降碳资金配置可持续性。',
    expectedOutcomeEn: 'Align board intention with operations metrics seamlessly.',
    expectedOutcomeZh: '打破董事会与部门中坚层在碳中和落实上的沟通壁垒，生成高度衔合的战略任务清单。'
  },
  'lead-2': {
    capabilityId: 'simulation',
    capabilityNameEn: 'AI Scenario Simulation',
    capabilityNameZh: 'AI 情景模拟',
    capabilityDescEn: 'Evaluate possible outcomes before implementing sustainability initiatives.',
    capabilityDescZh: '在实施管理措施前模拟可能结果。',
    icon: Compass,
    functionNameEn: 'Green HR Sandtable Attrition Pilot',
    functionNameZh: '管理制度压力与全员习惯留存演算',
    whySuitableEn: 'Runs predictive behavioral tests on talent friction when introducing carbon quotas or transit restrictions.',
    whySuitableZh: '针对诸如“限期禁驶高排汽车差旅、下班强制一键断电”等制度方案，推上演练对员工便利侵占的摩擦值。',
    benefitsEn: 'Averts structural active attrition risks by sizing administrative friction before actual codification.',
    benefitsZh: '防范因强力指令对研发进度、对白领午餐舒适度的极端碾压，避免核心高能人才因烦燥愤然离职。',
    sustContributionEn: 'Implements smart and highly stable climate transformation structures.',
    sustContributionZh: '在制度纸面颁布前获得最佳过度梯度预测方案，平稳降耗，保障转型稳定。',
    expectedOutcomeEn: 'Evaluate possible outcomes before implementing sustainability initiatives.',
    expectedOutcomeZh: '预测规章对人性的实际挤压，寻找“员工便利舒适度”与“用能极简度”的科学交融平衡。'
  },
  'lead-3': {
    capabilityId: 'generation',
    capabilityNameEn: 'AI Content Generation',
    capabilityNameZh: 'AI 内容生成',
    capabilityDescEn: 'Generate training materials, communication messages, sustainability campaigns, and management reports.',
    capabilityDescZh: '自动生成培训内容、宣传材料及管理报告。',
    icon: FileText,
    functionNameEn: 'Board Presentation Synthesizer',
    functionNameZh: '董事会无纸化成果决议案极速排汇',
    whySuitableEn: 'Assembles diverse green accomplishments into elegant boards slides showing metrics correlation.',
    whySuitableZh: '自动提取整年全园区“无底表、纸张消减、通勤低电”等绿色学堂绩效，翻译成可供核对的投影片。',
    benefitsEn: 'Saves the administration and corporate communication teams from endless chart scrubbing.',
    benefitsZh: '使负责撰写成果宣讲的团队从熬夜搜集素材的工作量中大松绑，提供坚实的一手环保红利证明。',
    sustContributionEn: 'Ensures direct board visibility of team sustainability score indicators.',
    sustContributionZh: '为组织二期降碳与节能改制计划争取更庞大的长期企业资金支持和顶层绿牌通行。',
    expectedOutcomeEn: 'Secure dynamic management consensus and unlock corporate development funds.',
    expectedOutcomeZh: '高屋建瓴归并环境学堂绩效和能碳账本，帮助部门负责人赢下领导层绝对认可。'
  }
};
